import * as path from "path";
import * as vscode from "vscode";
import {
  buildBibFromFields,
  extractPdfSignals,
  extractViaMistralAnnotation,
  rekey,
  resolveArxiv,
  resolveDoi,
} from "./bibExtract";
import { registerCiteHoverProvider } from "./citeHover";
import { registerCitePreview } from "./citePreview";
import { ocrModel, readApiKey, registerMistralOcrCommand } from "./mistralOcr";
import { statusBar } from "./status";
import { confirmAnnotationOcr, confirmReplace } from "./ui";

const BIB_FILENAME = "source.bib";
const BIB_GLOB = `**/sources/*/${BIB_FILENAME}`;
const AGGREGATE_FILENAME = "sources.bib";
const AGGREGATE_GLOB = `**/${AGGREGATE_FILENAME}`;
const AGGREGATE_BEGIN =
  "@Comment{WarpCite: BEGIN autogenerated - do not edit, everything between these markers is regenerated}";
const AGGREGATE_END = "@Comment{WarpCite: END autogenerated}";

export function activate(context: vscode.ExtensionContext): void {
  context.subscriptions.push(statusBar);
  registerMistralOcrCommand(context);
  registerCiteHoverProvider(context);
  registerCitePreview(context);

  void syncAllAggregates();

  const bibWatcher = vscode.workspace.createFileSystemWatcher(BIB_GLOB);
  bibWatcher.onDidCreate((uri) => scheduleAggregateSync(sourcesDirOf(uri)));
  bibWatcher.onDidChange((uri) => scheduleAggregateSync(sourcesDirOf(uri)));
  bibWatcher.onDidDelete((uri) => scheduleAggregateSync(sourcesDirOf(uri)));
  context.subscriptions.push(bibWatcher);

  const aggregateWatcher = vscode.workspace.createFileSystemWatcher(AGGREGATE_GLOB);
  aggregateWatcher.onDidDelete((uri) =>
    scheduleAggregateSync(vscode.Uri.joinPath(uri, "..", "sources"))
  );
  context.subscriptions.push(aggregateWatcher);

  context.subscriptions.push(
    vscode.workspace.onDidChangeWorkspaceFolders(() => void syncAllAggregates())
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("warpcite.copyAgentInstructions", async () => {
      const instructionsUri = vscode.Uri.joinPath(context.extensionUri, "AGENT_INSTRUCTIONS.md");
      try {
        const text = new TextDecoder().decode(
          await vscode.workspace.fs.readFile(instructionsUri)
        );
        await vscode.env.clipboard.writeText(text);
        vscode.window.showInformationMessage(
          "WarpCite: agent instructions copied to the clipboard."
        );
      } catch {
        vscode.window.showErrorMessage(
          "WarpCite: AGENT_INSTRUCTIONS.md not found in the extension."
        );
      }
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand("warpcite.generateBibtex", async (uri?: vscode.Uri) => {
      const pdfUri = uri ?? vscode.window.activeTextEditor?.document.uri;
      if (!pdfUri || !pdfUri.fsPath.toLowerCase().endsWith(".pdf")) {
        vscode.window.showErrorMessage("WarpCite: select a .pdf file to generate BibTeX for.");
        return;
      }
      await generateBibFor(pdfUri);
    })
  );
}

export function deactivate(): void {}

async function generateBibFor(pdfUri: vscode.Uri): Promise<void> {
  const pdfName = path.basename(pdfUri.fsPath);
  const bibUri = vscode.Uri.joinPath(pdfUri, "..", BIB_FILENAME);
  try {
    await vscode.workspace.fs.stat(bibUri);
    if (!(await confirmReplace(`${BIB_FILENAME} next to ${pdfName}`))) {
      return;
    }
  } catch {
    // source.bib does not exist yet
  }

  const citationKey = toCitationKey(path.basename(path.dirname(pdfUri.fsPath)));
  const actionId = statusBar.begin(`BibTeX ${pdfName} — analyzing PDF`);
  try {
    const data = await vscode.workspace.fs.readFile(pdfUri);

    // 1. identifier hunt (filename, text layer, metadata, link annotations)
    const signals = await extractPdfSignals(data, pdfName).catch(() => ({}) as PdfSignalsLike);
    let bibtex: string | undefined;
    let source = "";
    if (signals.arxivId) {
      statusBar.update(actionId, `BibTeX ${pdfName} — resolving arXiv:${signals.arxivId}`);
      bibtex = await resolveArxiv(signals.arxivId);
      source = `arXiv:${signals.arxivId}`;
    }
    if (!bibtex && signals.doi) {
      statusBar.update(actionId, `BibTeX ${pdfName} — resolving DOI ${signals.doi}`);
      bibtex = await resolveDoi(signals.doi);
      source = `DOI ${signals.doi}`;
    }
    if (bibtex) {
      const content = `@Comment{WarpCite: autogenerated for ${pdfName} (from ${source})}\n${rekey(bibtex, citationKey).trim()}\n`;
      await vscode.workspace.fs.writeFile(bibUri, new TextEncoder().encode(content));
      vscode.window.showInformationMessage(
        `WarpCite: created ${BIB_FILENAME} for ${pdfName} from ${source}.`
      );
      return;
    }

    // 2. no identifier — with the user's consent, run a Mistral OCR document
    //    annotation on the first two pages and build the entry from it
    if (await confirmAnnotationOcr(pdfName)) {
      const apiKey = await readApiKey();
      if (!apiKey) {
        vscode.window.showErrorMessage(
          "WarpCite: mistral-ocr-api.key not found in the workspace root."
        );
      } else {
        statusBar.update(actionId, `BibTeX ${pdfName} — running OCR annotation (first 2 pages)`);
        const fields = await extractViaMistralAnnotation(apiKey, data, pdfName, ocrModel()).catch(
          () => undefined
        );
        if (fields?.title) {
          const content = buildBibFromFields(fields, citationKey, pdfName);
          await vscode.workspace.fs.writeFile(bibUri, new TextEncoder().encode(content));
          vscode.window.showInformationMessage(
            `WarpCite: created ${BIB_FILENAME} for ${pdfName} from OCR annotation — please verify.`
          );
          return;
        }
      }
    }

    // 3. fallback (declined, missing key, or annotation failed): empty stub
    await vscode.workspace.fs.writeFile(bibUri, new TextEncoder().encode(bibTemplate(pdfUri)));
    vscode.window.showInformationMessage(
      `WarpCite: created an empty ${BIB_FILENAME} stub for ${pdfName}.`
    );
  } finally {
    statusBar.end(actionId);
  }
}

type PdfSignalsLike = { arxivId?: string; doi?: string };


function bibTemplate(pdfUri: vscode.Uri): string {
  const folderName = path.basename(path.dirname(pdfUri.fsPath));
  const pdfName = path.basename(pdfUri.fsPath);
  const citationKey = toCitationKey(folderName);
  return `@Comment{WarpCite: autogenerated for ${pdfName}}
@misc{${citationKey},
  title = {},
  author = {},
  note = {TODO: fill in citation (incl. year) for ${pdfName}},
}
`;
}

function toCitationKey(name: string): string {
  const key = name.replace(/[^A-Za-z0-9_-]/g, "");
  return key.length > 0 ? key : "source";
}

// --- sources.bib aggregation ---------------------------------------------

/** The `sources` folder two levels above a `sources/<x>/<file>` uri. */
function sourcesDirOf(uri: vscode.Uri): vscode.Uri {
  return vscode.Uri.joinPath(uri, "..", "..");
}

async function syncAllAggregates(): Promise<void> {
  const bibs = await vscode.workspace.findFiles(BIB_GLOB, "**/node_modules/**");
  const sourcesDirs = new Map<string, vscode.Uri>();
  for (const uri of bibs) {
    const dir = sourcesDirOf(uri);
    sourcesDirs.set(dir.toString(), dir);
  }
  for (const dir of sourcesDirs.values()) {
    scheduleAggregateSync(dir);
  }
}

const pendingSyncs = new Map<string, ReturnType<typeof setTimeout>>();

/** Coalesce bursts of file events into one aggregate rebuild per sources dir. */
function scheduleAggregateSync(sourcesDirUri: vscode.Uri): void {
  const key = sourcesDirUri.toString();
  const pending = pendingSyncs.get(key);
  if (pending) {
    clearTimeout(pending);
  }
  pendingSyncs.set(
    key,
    setTimeout(() => {
      pendingSyncs.delete(key);
      void syncAggregate(sourcesDirUri);
    }, 300)
  );
}

async function syncAggregate(sourcesDirUri: vscode.Uri): Promise<void> {
  let entries: [string, vscode.FileType][];
  try {
    entries = await vscode.workspace.fs.readDirectory(sourcesDirUri);
  } catch {
    return; // sources dir is gone
  }

  const decoder = new TextDecoder();
  const parts: string[] = [];
  for (const [name, type] of entries.sort((a, b) => a[0].localeCompare(b[0]))) {
    if (type !== vscode.FileType.Directory) {
      continue;
    }
    const bibUri = vscode.Uri.joinPath(sourcesDirUri, name, BIB_FILENAME);
    try {
      const raw = decoder.decode(await vscode.workspace.fs.readFile(bibUri));
      const part = `@Comment{WarpCite: from ${path.basename(sourcesDirUri.fsPath)}/${name}/${BIB_FILENAME}}\n${raw.trim()}`;
      parts.push(collapseBlankLinesAfterComments(part));
    } catch {
      // this subfolder has no source.bib
    }
  }

  const aggregateUri = vscode.Uri.joinPath(sourcesDirUri, "..", AGGREGATE_FILENAME);
  let existing: string | undefined;
  try {
    existing = decoder.decode(await vscode.workspace.fs.readFile(aggregateUri));
  } catch {
    // sources.bib does not exist yet
  }
  if (existing === undefined && parts.length === 0) {
    return;
  }

  const manual = stripAutogeneratedBlock(existing ?? "").trimEnd();
  const block = [AGGREGATE_BEGIN, ...parts, AGGREGATE_END].join("\n\n");
  const next = manual.length > 0 ? `${manual}\n\n${block}\n` : `${block}\n`;
  if (next !== existing) {
    await vscode.workspace.fs.writeFile(aggregateUri, new TextEncoder().encode(next));
  }
}

/** A comment line attaches directly to the line that follows it; blank lines only separate entries. */
function collapseBlankLinesAfterComments(text: string): string {
  return text.replace(/(@Comment\{[^\n]*\})\n{2,}/g, "$1\n");
}

function stripAutogeneratedBlock(text: string): string {
  let result = text;
  let begin: number;
  while ((begin = result.indexOf(AGGREGATE_BEGIN)) !== -1) {
    const endMarker = result.indexOf(AGGREGATE_END, begin);
    const end = endMarker === -1 ? result.length : endMarker + AGGREGATE_END.length;
    result = result.slice(0, begin) + result.slice(end);
  }
  return result;
}
